services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=finalnodejs
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    networks:
      - midterm-network
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=finalnodejs
    ports:
      - "8083:8080"
    volumes:
      - ./frontend/views:/usr/src/app/frontend/views
      - ./public:/usr/src/app/public
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "start"]
    working_dir: /usr/src/app
    networks:
      - midterm-network
    restart: always

  backend2:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=finalnodejs
    ports:
      - "8084:8080"
    volumes:
      - ./frontend/views:/usr/src/app/frontend/views
      - ./public:/usr/src/app/public
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "start"]
    working_dir: /usr/src/app
    networks:
      - midterm-network
    restart: always

  nginx:
    build: 
      context: ./docker/frontend-nginx
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - midterm-network
    depends_on:
      - backend
      - backend2
    volumes:
      - ./frontend/views:/usr/share/nginx/html
      - ./production/default.conf:/etc/nginx/conf.d/default.conf

networks:
  midterm-network:
    driver: bridge

volumes:
  mysql-data:
